data:
  dataflg: era5
  grid_res: 2
  input_path:
  - /scratch/users/linyao/ML4MJO/data/fltano120/olr.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/prep.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/tcwv.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/sst.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/q200.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/q500.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/q850.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/T200.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/T500.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/T850.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/u200.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/u500.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/u850.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/v200.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/v500.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/v850.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/Z200.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/Z500.fltano120.1978to2025based1979to2001.nc
  - /scratch/users/linyao/ML4MJO/data/fltano120/Z850.fltano120.1978to2025based1979to2001.nc
  input_vars:
  - olr
  - prep
  - tcwv
  - sst
  - q200
  - q500
  - q850
  - T200
  - T500
  - T850
  - u200
  - u500
  - u850
  - v200
  - v500
  - v850
  - Z200
  - Z500
  - Z850
  lat_range: 20
  lead: 5
  target_path: /scratch/users/linyao/ML4MJO/data/targets/ROMI_ERA5_daily_1979to2012.nc
  target_vars:
  - ROMI
  test_end: '2021-12-31'
  test_start: '2010-01-01'
  train_end: '2009-12-31'
  train_start: '1980-01-01'
  transform: null
  val_end: '2015-12-31'
  val_start: '2010-01-01'
dataset_type: map
exp_num: 16
hidden_layers_str: '512_192_16'
kernel_size_str: '7_7'
model:
  cnn:
    channels_list:
    - 32
    - 32
    channels_list_str: '64'
    dropout: 0.0
    input_channel_num: 19
    input_map_size: 3780
    kernel_size:
    - 7
    - 7
    nlat: 21
    nlon: 180
    norm_type: batch
    num_filters_enc: 64
    num_groups: 0
    padding: same
    stride: 1
  mlp:
    dropout: 0.30000000000000004
    hidden_layers:
    - 512
    - 192
    - 16
    output_size: 2
    use_layer_norm: true
  name: UNet_A
model_save_path: /scratch/users/linyao/ML4MJO/scripts/outputs/models/era5_BEST_UNet_A_ROMI_lead5/UNet_A/ROMI/lead5/t1/exp16/model_lr0.0013718288075993254_bs48_do0.30000000000000004_cnn64_k7_7_mlp512_192_16_SGD.pt
prediction_save_path: /scratch/users/linyao/ML4MJO/scripts/outputs/predictions/era5_BEST_UNet_A_ROMI_lead5/UNet_A/ROMI/lead5/t1/exp16/preds_lr0.0013718288075993254_bs48_do0.30000000000000004_cnn64_k7_7_mlp512_192_16_SGD.nc
training:
  batch_size: 48
  criterion: MSELoss
  early_stopping_patience: 7
  epochs: 20
  learning_rate: 0.0013718288075993254
  momentum: 0.95
  multi_lead: false
  optimizer: SGD
  weight_decay: 3.1171315598073666e-05
