import os
import yaml
import copy
import optuna
import numpy as np
import sys
from pathlib import Path
import torch

# Add src/ and scripts/ to sys.path
scripts_path = Path(__file__).resolve().parents[2]
sys.path.append(str(scripts_path))
sys.path.append(str(scripts_path / 'src'))

from data_prepare.dataset import load_train_data, load_val_data, load_test_data, get_time_dimension
from models.cnnmlp import CNNMLP
from models.unet import UNet_A
from trainers.train import train_model
from inference.predict import predict
from utils.save_prediction import save_predictions_with_time
from utils.logger import setup_logger

logger = setup_logger()

'''
Load a specific top-N trial from the combined pool of multiple studies, 
then train and evaluate.

Environment variables:
  trial_rank : 1..5 (1=best, 2=second-best, ... across all combined studies)
  exp_num    : 1..8 (random repetition index)
  dataflg    : dataset flag (e.g., era5, noaa)
  expflg     : experiment/input dir flag (e.g., rescaled_m10resi_wnx9resi)
  input_var  : input variable name (e.g., olr)
  output_var : output variable name (e.g., ROMI)
  model_name : model name (e.g., CNN_MLP, UNet_A)

Example:
  trial_rank=1 exp_num=1 dataflg=era5 python3 a2_best.py
'''

# ======================================================================
# 1. Read Environment Variables
# ======================================================================
exp_num = int(os.environ.get("exp_num", 1))
trial_rank = int(os.environ.get("trial_rank", 1))   
N_TOP = 5                                           

dataflg = os.environ.get("dataflg", "era5").lower()
input_dir = os.environ.get("expflg", "rescaled_m10all_wnx1off")
input_var_name = os.environ.get("input_var", "olr")
output_var_name = os.environ.get("output_var", "ROMI")
model_name = os.environ.get("model_name", "UNet_A")
saveall = os.environ.get("saveall", "true").lower() == "true"
multi_lead = os.environ.get("multi_lead", "true").lower() == "true"

# Generate exact exp_name matching hpo.py
if not multi_lead:
    lead = int(os.environ.get("lead", 0))
    exp_name = f"{dataflg}_{input_var_name}_{model_name}_{output_var_name}_{input_dir}_lead{lead}"
else:
    exp_name = f"{dataflg}_{input_var_name}_{model_name}_{output_var_name}_{input_dir}"

# ======================================================================
# 2. Load the Base Configuration generated by HPO
# ======================================================================
config_path = f'./yaml/hpo_{exp_name}.yaml'
if not os.path.exists(config_path):
    raise FileNotFoundError(f"Config file {config_path} not found. Did you run hpo.py?")

with open(config_path, "r") as f:
    base_config = yaml.safe_load(f)

# ======================================================================
# 3. Load Optuna Studies and Extract Top Trial
# ======================================================================
optuna_dir = "./optuna"
all_trials = []

# Assuming you still want to pool across Study 1 and Study 2
for study_id in [1, ]:
    study_name = f"{exp_name}_s{study_id}"
    storage_path = os.path.join(optuna_dir, f"{study_name}.db")
    
    if os.path.exists(storage_path):
        logger.info(f"Loading Optuna study: {study_name} from {storage_path}")
        study = optuna.load_study(study_name=study_name, storage=f"sqlite:///{storage_path}")
        completed = [t for t in study.trials if t.state == optuna.trial.TrialState.COMPLETE]
        all_trials.extend(completed)
    else:
        logger.warning(f"Optuna study database not found at {storage_path}.")

if not all_trials:
    raise FileNotFoundError("No completed trials found across requested studies. Run hpo.py first.")

# Sort combined trials by value (minimize val_loss)
top_trials = sorted(all_trials, key=lambda t: t.value)[:N_TOP]

if len(top_trials) < trial_rank:
    raise ValueError(f"Only {len(top_trials)} combined completed trials found, but trial_rank={trial_rank} requested.")

selected_trial = top_trials[trial_rank - 1] 
best_params = selected_trial.params

logger.info(f"=== Selected Global Trial Rank: {trial_rank} (Trial #{selected_trial.number}) ===")
logger.info(f"Validation Loss: {selected_trial.value:.6f}")
logger.info(f"Hyperparameters: {best_params}")

# ======================================================================
# 4. Apply Hyperparameters to Config
# ======================================================================
config = copy.deepcopy(base_config)
config["exp_num"] = exp_num

# --- HPO: Normalization ---
norm_type = best_params["norm_type"]
num_groups = 8 if norm_type == "group" else 0 

# --- HPO: CNN Architecture ---
if config["model"]["name"] == "CNN_MLP":
    n_filters = best_params["num_filters_enc"]
    config["model"]["cnn"]["channels_list"] = [n_filters, n_filters]
    config["model"]["cnn"]["channels_list_str"] = f"{n_filters}_{n_filters}"
else: # UNet_A
    n_filters = best_params["num_filters_enc"]
    config["model"]["cnn"]["num_filters_enc"] = n_filters
    config["model"]["cnn"]["channels_list_str"] = str(n_filters)

grid_res = float(config["data"]["grid_res"])
lat_range = config["data"]["lat_range"]
nlon = int(np.floor(360 / grid_res))
nlat = int(np.floor(lat_range / grid_res) * 2 + 1)

config["model"]["cnn"].update({
    "input_channel_num": len(config["data"]["input_path"]),
    "input_map_size": nlon * nlat,
    "norm_type": norm_type,
    "num_groups": num_groups,
    "dropout": 0.0,
    "nlon": nlon,
    "nlat": nlat
})

k_size = best_params["kernel_size"]
config["model"]["cnn"]["kernel_size"] = [k_size, k_size]
config["kernel_size_str"] = f"{k_size}_{k_size}"

# --- HPO: MLP Architecture ---
lead = config["data"]["lead"]
multi_lead = config["training"].get("multi_lead", True)
n_modes = 2 
output_size = (lead + 1) * n_modes if multi_lead else n_modes

h1 = best_params["nhidden1"]
h2 = best_params["nhidden2"]
h3 = best_params["nhidden3"]

config["model"]["mlp"].update({
    "hidden_layers": [h1, h2, h3],
    "output_size": output_size,
    "dropout": best_params["dropout_rate"]
})
config["hidden_layers_str"] = f"{h1}_{h2}_{h3}"

# --- HPO: Training Params ---
optimizer_name = best_params["optimizer"]
momentum = best_params["momentum"] if optimizer_name == "SGD" else 0.9

config["training"].update({
    "optimizer": optimizer_name,
    "learning_rate": best_params["learning_rate"],
    "weight_decay": best_params["weight_decay"],
    "momentum": momentum,
    "batch_size": best_params["batch_size"],
    "epochs": 20, 
    "early_stopping_patience": 7
})

# ======================================================================
# 5. Build Save Paths
# ======================================================================
trial_tag = f"t{trial_rank}"

save_kwargs = {
    "dataset_type": exp_name,
    "exp_num": f"{trial_tag}/exp{config['exp_num']}",
    "lat_range": config["data"]["lat_range"],
    "lead": lead,
    "lr": config["training"]["learning_rate"],
    "batch_size": config["training"]["batch_size"],
    "dropout": config["model"]["mlp"]["dropout"],
    "channels_list_str": config["model"]["cnn"]["channels_list_str"],
    "kernel_size": config["kernel_size_str"],
    "hidden_layers_str": config["hidden_layers_str"],
    "optimizer": config["training"]["optimizer"],
    "model_name": config["model"]["name"],
    "target_name": config["data"]["target_vars"][0]
}

# Define the path templates directly in the script
base_pred_path = "/scratch/users/linyao/ML4MJO/scripts/outputs/predictions/{dataset_type}/{model_name}/{target_name}/lead{lead}/{exp_num}/preds_lr{lr}_bs{batch_size}_do{dropout}_cnn{channels_list_str}_k{kernel_size}_mlp{hidden_layers_str}_{optimizer}.nc"
base_model_path = "/scratch/users/linyao/ML4MJO/scripts/outputs/models/{dataset_type}/{model_name}/{target_name}/lead{lead}/{exp_num}/model_lr{lr}_bs{batch_size}_do{dropout}_cnn{channels_list_str}_k{kernel_size}_mlp{hidden_layers_str}_{optimizer}.pt"

# Format them and save back to config
config["prediction_save_path"] = base_pred_path.format(**save_kwargs)
config["model_save_path"] = base_model_path.format(**save_kwargs)

prediction_save_path = config["prediction_save_path"]
model_save_path = config["model_save_path"]

if os.path.exists(prediction_save_path):
    print(f"{prediction_save_path} exists. exit.")
    sys.exit(0)
    # os.remove(prediction_save_path)

# =====================================================================
# 6. Execution: Load Data, Build Model, Train
# =====================================================================
train_loader = load_train_data(config)
val_loader = load_val_data(config)

if config["model"]["name"] == "CNN_MLP":
    model = CNNMLP(config["model"]["cnn"], config["model"]["mlp"])
elif config["model"]["name"] == "UNet_A":
    model = UNet_A(config["model"]["cnn"], config["model"]["mlp"])
else:
    raise ValueError(f"Unsupported model: {config['model']['name']}")

logger.info(f"Training combined trial_rank={trial_rank} exp={exp_num} started...")
trained_model = train_model(model, train_loader, val_loader, config)

# =====================================================================
# 7. Save Model Weights
# =====================================================================
if saveall:
    os.makedirs(os.path.dirname(model_save_path), exist_ok=True)
    if os.path.exists(model_save_path):
        os.remove(model_save_path)
        logger.info(f"{model_save_path} exists. Removed previous version.")
    torch.save(trained_model.state_dict(), model_save_path)
    logger.info(f"Best model saved at {model_save_path}")

# =====================================================================
# 8. Inference / Predictions
# =====================================================================
logger.info(f"Making predictions on test data for lead={lead}...")
test_loader = load_test_data(config)

trained_model = trained_model.cuda()
preds = predict(trained_model, test_loader)
targets = torch.cat([batch[1] for batch in test_loader], dim=0).cpu()

time = get_time_dimension(
    config["data"]["input_path"],
    config["data"]["test_start"],
    config["data"]["test_end"],
    config["data"]["lead"],
)

if len(time) != preds.shape[0] or len(time) != targets.shape[0]:
    raise ValueError(
        f"Dimension mismatch: Time length ({len(time)}) does not match "
        f"predictions ({preds.shape[0]}) or targets ({targets.shape[0]})."
    )

os.makedirs(os.path.dirname(prediction_save_path), exist_ok=True)
save_predictions_with_time(preds, targets, time, prediction_save_path)
logger.info(f"Predictions saved successfully at {prediction_save_path}")

# Save the finalized config
config_out = f'./yaml/best_config_{exp_name}_{trial_tag}.yaml'
with open(config_out, 'w') as f:
    yaml.dump(config, f)

