data:
  dataflg: era5
  grid_res: 2
  input_path:
  - /scratch/users/linyao/ML4MJO/data/unscaled_m10all_wnx1off/olr.fltano120.1978to2025based1979to2001.nc
  input_vars:
  - olr
  lat_range: 20
  lead: 5
  target_path: /scratch/users/linyao/ML4MJO/data/targets/RMM_ERA5_daily_1979to2001.nc
  target_vars:
  - RMM
  test_end: '2021-12-31'
  test_start: '2010-01-01'
  train_end: '2009-12-31'
  train_start: '1980-01-01'
  transform: null
  val_end: '2015-12-31'
  val_start: '2010-01-01'
dataset_type: map
exp_num: 4
hidden_layers_str: '256_128_64'
kernel_size_str: '7_7'
model:
  cnn:
    channels_list:
    - 32
    - 32
    channels_list_str: '64'
    dropout: 0.0
    input_channel_num: 1
    input_map_size: 3780
    kernel_size:
    - 7
    - 7
    nlat: 21
    nlon: 180
    norm_type: batch
    num_filters_enc: 64
    num_groups: 0
    padding: same
    stride: 1
  mlp:
    dropout: 0.2
    hidden_layers:
    - 256
    - 128
    - 64
    output_size: 2
    use_layer_norm: true
  name: UNet_A
model_save_path: /scratch/users/linyao/ML4MJO/scripts/outputs/models/era5_olr_UNet_A_RMM_unscaled_m10all_wnx1off_lead5/UNet_A/RMM/lead5/t1/exp4/model_lr0.002176475030396079_bs48_do0.2_cnn64_k7_7_mlp256_128_64_SGD.pt
prediction_save_path: /scratch/users/linyao/ML4MJO/scripts/outputs/predictions/era5_olr_UNet_A_RMM_unscaled_m10all_wnx1off_lead5/UNet_A/RMM/lead5/t1/exp4/preds_lr0.002176475030396079_bs48_do0.2_cnn64_k7_7_mlp256_128_64_SGD.nc
training:
  batch_size: 48
  criterion: MSELoss
  early_stopping_patience: 7
  epochs: 20
  learning_rate: 0.002176475030396079
  momentum: 0.95
  multi_lead: false
  optimizer: SGD
  weight_decay: 0.00012861318075968155
