data:
  dataflg: era5
  grid_res: 2
  input_path:
  - /scratch/users/linyao/ML4MJO/data/unscaled_m5all_wnx9all/olr.fltano120.1978to2025based1979to2001.nc
  input_vars:
  - olr
  lat_range: 20
  lead: 10
  target_path: /scratch/users/linyao/ML4MJO/data/targets/RMM_ERA5_daily_1979to2001.nc
  target_vars:
  - RMM
  test_end: '2021-12-31'
  test_start: '2010-01-01'
  train_end: '2009-12-31'
  train_start: '1980-01-01'
  transform: null
  val_end: '2015-12-31'
  val_start: '2010-01-01'
dataset_type: map
exp_num: 16
hidden_layers_str: '384_192_64'
kernel_size_str: '5_5'
model:
  cnn:
    channels_list:
    - 32
    - 32
    channels_list_str: '64'
    dropout: 0.0
    input_channel_num: 1
    input_map_size: 3780
    kernel_size:
    - 5
    - 5
    nlat: 21
    nlon: 180
    norm_type: batch
    num_filters_enc: 64
    num_groups: 0
    padding: same
    stride: 1
  mlp:
    dropout: 0.4
    hidden_layers:
    - 384
    - 192
    - 64
    output_size: 2
    use_layer_norm: true
  name: UNet_A
model_save_path: /scratch/users/linyao/ML4MJO/scripts/outputs/models/era5_olr_UNet_A_RMM_unscaled_m5all_wnx9all_lead10/UNet_A/RMM/lead10/t1/exp16/model_lr0.015781454322325736_bs48_do0.4_cnn64_k5_5_mlp384_192_64_SGD.pt
prediction_save_path: /scratch/users/linyao/ML4MJO/scripts/outputs/predictions/era5_olr_UNet_A_RMM_unscaled_m5all_wnx9all_lead10/UNet_A/RMM/lead10/t1/exp16/preds_lr0.015781454322325736_bs48_do0.4_cnn64_k5_5_mlp384_192_64_SGD.nc
training:
  batch_size: 48
  criterion: MSELoss
  early_stopping_patience: 7
  epochs: 20
  learning_rate: 0.015781454322325736
  momentum: 0.9
  multi_lead: false
  optimizer: SGD
  weight_decay: 0.0001933163501942743
