data:
  dataflg: noaa
  grid_res: 2
  input_path:
  - /scratch/users/linyao/ML4MJO/data/unscaled_m10all_wnx1off/olr.fltano120.noaa.2x2.1979to2022based1979to2001.nc
  input_vars:
  - olr
  lat_range: 20
  lead: 35
  target_path: /scratch/users/linyao/ML4MJO/data/targets/noaa/ROMI_NOAA_1979to2022.nc
  target_vars:
  - ROMI
  test_end: '2021-12-31'
  test_start: '2010-01-01'
  train_end: '2009-12-31'
  train_start: '1980-01-01'
  transform: null
  val_end: '2015-12-31'
  val_start: '2010-01-01'
dataset_type: map
exp_num: 1
hidden_layers_str: '512_64_80'
kernel_size_str: '9_9'
model:
  cnn:
    channels_list:
    - 32
    - 32
    channels_list_str: '16'
    dropout: 0.0
    input_channel_num: 1
    input_map_size: 3780
    kernel_size:
    - 9
    - 9
    nlat: 21
    nlon: 180
    norm_type: group
    num_filters_enc: 16
    num_groups: 8
    padding: same
    stride: 1
  mlp:
    dropout: 0.30000000000000004
    hidden_layers:
    - 512
    - 64
    - 80
    output_size: 2
    use_layer_norm: true
  name: UNet_A
model_save_path: /scratch/users/linyao/ML4MJO/scripts/outputs/models/noaa_olr_UNet_A_ROMI_unscaled_m10all_wnx1off_lead35/UNet_A/ROMI/lead35/t1/exp1/model_lr0.008662352119999285_bs32_do0.30000000000000004_cnn16_k9_9_mlp512_64_80_SGD.pt
prediction_save_path: /scratch/users/linyao/ML4MJO/scripts/outputs/predictions/noaa_olr_UNet_A_ROMI_unscaled_m10all_wnx1off_lead35/UNet_A/ROMI/lead35/t1/exp1/preds_lr0.008662352119999285_bs32_do0.30000000000000004_cnn16_k9_9_mlp512_64_80_SGD.nc
training:
  batch_size: 32
  criterion: MSELoss
  early_stopping_patience: 7
  epochs: 20
  learning_rate: 0.008662352119999285
  momentum: 0.95
  multi_lead: false
  optimizer: SGD
  weight_decay: 0.0004936838783673767
