data:
  dataflg: era5
  grid_res: 2
  input_path:
  - /scratch/users/linyao/ML4MJO/data/fltano120/olr.fltano120.1978to2025based1979to2001.nc
  input_vars:
  - olr
  lat_range: 20
  lead: 0
  target_path: /scratch/users/linyao/ML4MJO/data/targets/RMM_ERA5_daily_1979to2001.nc
  target_vars:
  - RMM
  test_end: '2021-12-31'
  test_start: '2010-01-01'
  train_end: '2009-12-31'
  train_start: '1980-01-01'
  transform: null
  val_end: '2015-12-31'
  val_start: '2010-01-01'
dataset_type: map
exp_num: 11
hidden_layers_str: '256_256_16'
kernel_size_str: '5_5'
model:
  cnn:
    channels_list:
    - 48
    - 48
    channels_list_str: '48_48'
    dropout: 0.0
    input_channel_num: 1
    input_map_size: 3780
    kernel_size:
    - 5
    - 5
    nlat: 21
    nlon: 180
    norm_type: batch
    num_filters_enc: 16
    num_groups: 0
    padding: same
    stride: 1
  mlp:
    dropout: 0.1
    hidden_layers:
    - 256
    - 256
    - 16
    output_size: 2
    use_layer_norm: true
  name: CNN_MLP
model_save_path: /scratch/users/linyao/ML4MJO/scripts/outputs/models/era5_olr_CNN_MLP_RMM_fltano120_lead0/CNN_MLP/RMM/lead0/t1/exp11/model_lr0.004205498447127502_bs16_do0.1_cnn48_48_k5_5_mlp256_256_16_SGD.pt
prediction_save_path: /scratch/users/linyao/ML4MJO/scripts/outputs/predictions/era5_olr_CNN_MLP_RMM_fltano120_lead0/CNN_MLP/RMM/lead0/t1/exp11/preds_lr0.004205498447127502_bs16_do0.1_cnn48_48_k5_5_mlp256_256_16_SGD.nc
training:
  batch_size: 16
  criterion: MSELoss
  early_stopping_patience: 7
  epochs: 20
  learning_rate: 0.004205498447127502
  momentum: 0.95
  multi_lead: false
  optimizer: SGD
  weight_decay: 3.304444031974361e-05
