data:
  dataflg: era5
  grid_res: 2
  input_path:
  - /scratch/users/linyao/ML4MJO/data/fltano120/q850.fltano120.1978to2025based1979to2001.nc
  input_vars:
  - q850
  lat_range: 20
  lead: 35
  target_path: /scratch/users/linyao/ML4MJO/data/targets/RMM_ERA5_daily_1979to2001.nc
  target_vars:
  - RMM
  test_end: '2021-12-31'
  test_start: '2010-01-01'
  train_end: '2009-12-31'
  train_start: '1980-01-01'
  transform: null
  val_end: '2015-12-31'
  val_start: '2010-01-01'
dataset_type: map
exp_num: 16
hidden_layers_str: '256_192_96'
kernel_size_str: '3_3'
model:
  cnn:
    channels_list:
    - 32
    - 32
    channels_list_str: '48'
    dropout: 0.0
    input_channel_num: 1
    input_map_size: 3780
    kernel_size:
    - 3
    - 3
    nlat: 21
    nlon: 180
    norm_type: batch
    num_filters_enc: 48
    num_groups: 0
    padding: same
    stride: 1
  mlp:
    dropout: 0.30000000000000004
    hidden_layers:
    - 256
    - 192
    - 96
    output_size: 72
    use_layer_norm: true
  name: UNet_A
model_save_path: /scratch/users/linyao/ML4MJO/scripts/outputs/models/era5_q850_UNet_A_RMM_fltano120/UNet_A/RMM/lead35/t1/exp16/model_lr0.012094997329507523_bs48_do0.30000000000000004_cnn48_k3_3_mlp256_192_96_SGD.pt
prediction_save_path: /scratch/users/linyao/ML4MJO/scripts/outputs/predictions/era5_q850_UNet_A_RMM_fltano120/UNet_A/RMM/lead35/t1/exp16/preds_lr0.012094997329507523_bs48_do0.30000000000000004_cnn48_k3_3_mlp256_192_96_SGD.nc
training:
  batch_size: 48
  criterion: MSELoss
  early_stopping_patience: 7
  epochs: 20
  learning_rate: 0.012094997329507523
  momentum: 0.8
  multi_lead: true
  optimizer: SGD
  weight_decay: 0.0001070867121400418
